/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-12-19 08:13:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class queryscore_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String chk;
  private java.lang.String txt1;
  private java.lang.String rd;

  public java.lang.String getChk() {
    return this.chk;
  }

  public void setChk(java.lang.String chk) {
    this.chk = chk;
    jspContext.setAttribute("chk", chk);
  }

  public java.lang.String getTxt1() {
    return this.txt1;
  }

  public void setTxt1(java.lang.String txt1) {
    this.txt1 = txt1;
    jspContext.setAttribute("txt1", txt1);
  }

  public java.lang.String getRd() {
    return this.rd;
  }

  public void setRd(java.lang.String rd) {
    this.rd = rd;
    jspContext.setAttribute("rd", rd);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getChk() != null ) 
      _jspx_page_context.setAttribute("chk", getChk());
    if( getTxt1() != null ) 
      _jspx_page_context.setAttribute("txt1", getTxt1());
    if( getRd() != null ) 
      _jspx_page_context.setAttribute("rd", getRd());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

					try {
						Class.forName("com.mysql.jdbc.Driver");
					} catch (Exception e) {
					}
					try {
						String url = "jdbc:mysql://localhost/score";
						String user = "root";
						String password = "";
						Connection con = DriverManager.getConnection(url, user, password);
						request.setCharacterEncoding("utf-8");
						
						if(rd==null)
							rd="student.sid";
						Statement sql = con.createStatement();
						String sql1 = "SELECT student.sid,sname,cname,grade FROM student JOIN score ON student.sid=score.sid JOIN course ON course.cid=score.cid where "
								+ chk + " like '%" + txt1 + "%' order by "+rd+" desc";
						ResultSet rs = sql.executeQuery(sql1);
						out.print("<table border=1 align='center'><tr><th width='300px'>学号</th><th width='300px'>名字</th><th width='300px'>课程名称</th><th width='300px'>成绩</th></tr>");
						while (rs.next()) {
							out.print("<tr><td width='100px' height='30px' align='center'>" + rs.getInt(1) + "</td>");
							out.print("<td width='300px' height='30px' align='center'>" + rs.getString(2) + "</td>");
							out.print("<td width='300px' height='30px' align='center'>" + rs.getString(3) + "</td>");
							out.print("<td width='300px' height='30px' align='center'>" + rs.getFloat(4) + "</td>");
						}
						out.print("</table>");
						con.close();
					} catch (SQLException e) {
						out.print(e);
					}
				
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
